### PR TITLE
Rebase

### PR DESCRIPTION
**Pull request by ThatZiv**
## Describe your changes

Merge main to development to keep commits leveled. I should've done that previous PR to development instead of main

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] There are no lint nor build errors in my code.
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Review by XLRA — APPROVED** [review]
Everything checks out, LGTM!

**Comment by PierreT20** [comment]
Checks out looks good to merge to dev

**Review by PierreT20 — APPROVED** [review]
Looks to me

**Comment by XLRA** [comment]
This rebase was really needed for a complete overhaul of the website. Looking back this change was really good to completely transform the front user landing page today!

**Pull request merged**
