### PR TITLE
Updating Front-End

### PR DESCRIPTION
**Pull request by SukrutN**
**Description:**
This pull request introduces updates to the front end of the project, enhancing user experience and aligning with the latest design standards. The changes encompass UI enhancements, improvements to stylesheets, and optimizations to client-side scripts.

**Changes Proposed:**

Updated UI components to improve usability and visual appeal.
Refactored stylesheets for better organization and maintainability.
Implemented optimizations in client-side scripts to enhance performance.
Ensured responsiveness across various devices and screen sizes.

### CODE REVIEW

**Review by ThatZiv — CHANGES_REQUESTED** [review]
The build job is failing during linting. I would tackle those pesky type errors here:
https://github.com/WSU-4110/TrophyTracker/actions/runs/7840626843/job/21395541072?pr=44#step:5:42
or run `npm run lint` locally. Install the eslint vscode extension so those type errors show up too.

**Review by ThatZiv — APPROVED** [review]
Seems like it's working. This PRs been open and I don't want to keep you hanging here so we can either:
- Merge now, fix all the issues I mentioned (mainly removed everything that's uneeded - the repo is already bloated and i'm not entirely sure what's needed and what's not) - this will make refactoring and further development not a complete pain for the rest of us.
- Or, keep this PR open and request changes when you're ready.

Up to you. Thoughts team @WSU-4110/trophytracker ??

**Comment by SukrutN** [comment]
I believe we should merge this in and then I can work on pruning the portions of the code that are redundant or issue causing

**Comment by SukrutN** [comment]
> I believe we should merge this in and then I can work on pruning the portions of the code that are redundant or issue causing

@ThatZiv

**Comment by XLRA** [comment]
As long as we can prune the portions of the code that are redundant and have no merging conflicts with Zavaar's branch this will work for me. Looking through we can merge it.

**Pull request merged**
